#+TITLE: mq (maths questions)
#+AUTHOR: noisytoot
This file is about mq version 1.3.0
* What is mq?
  mq is a program that asks you maths questions
* How to use?
  mq <mode> <max>
  - Mode "level1" :: Addition, subtraction
  - Mode "level2" :: Multiplication, division
  - Mode "get-group" :: Get the group length
  - Mode "get-max" :: Get the maximum number
  - Optional named argument "disable-log" :: Disable the log file
  Example: ~mq --disable-log level1 10~
* Configuration file
** Where is the configuration file?
   The location is set in the environment variable $MQ_CONFIG, if $MQ_CONFIG does not exist then it is in ~/.mq/config.toml
** What format is it in?
   It is written in TOML 0.4.0
** What keys/sections are there?
*** The section "mq"
    - The integer "group" :: The length of the group, can be set to any integer
** What does it look like?
#+BEGIN_SRC toml
[mq]
group = 20
length = 10
#+END_SRC
* Log file
** Where is the log file?
   The location is set in the environment variable $MQ_LOG, if $MQ_LOG does not exist then it is in ~/.mq/log.slf
** What format is it in?
   SLF (The Simple Log Format), basically CSV/DSV separated with spaces
